# Generated by Django 2.2.24 on 2022-04-29 17:00
import phonenumbers

from django.db import migrations


def do_clear_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        bad_phone = flat.owners_phonenumber
        parsed_phone = phonenumbers.parse(
            bad_phone, 'RU'
        )
        if phonenumbers.is_valid_number(parsed_phone):
            good_phone = f'+{parsed_phone.country_code}{parsed_phone.national_number}'
            flat.owner_pure_phone = good_phone
            flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        flat.owner_pure_phone = ''
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(do_clear_number, move_backward)
    ]
