# Generated by Django 2.2.24 on 2022-05-01 10:50

from django.db import migrations


def fill_flats_in_owner_model(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, _ = Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            defaults={
                'owner_pure_phone': flat.owner_pure_phone,
            }
        )
        owner.flats.set([flat])
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20220501_1736'),
    ]

    operations = [
        migrations.RunPython(fill_flats_in_owner_model)
    ]
